// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnnykaLTNMF0t_qmYbfT_PwAtZF1vntsM',
    appId: '1:761169513958:web:1fbebecba93f0203ccda27',
    messagingSenderId: '761169513958',
    projectId: 'my-tictok-practice',
    authDomain: 'my-tictok-practice.firebaseapp.com',
    storageBucket: 'my-tictok-practice.appspot.com',
    measurementId: 'G-F00MHKG7H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj-Iz6LW9ygLML_8a46A3G6hmwdhuwUHk',
    appId: '1:761169513958:android:f13639fd859dc855ccda27',
    messagingSenderId: '761169513958',
    projectId: 'my-tictok-practice',
    storageBucket: 'my-tictok-practice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9HJE-ZzpkQO-B8JQdfxy31G8naF8VJeo',
    appId: '1:761169513958:ios:be4d5fc8d82bdc08ccda27',
    messagingSenderId: '761169513958',
    projectId: 'my-tictok-practice',
    storageBucket: 'my-tictok-practice.appspot.com',
    iosBundleId: 'com.example.tiktokCloneAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBut0ecAdRTg-ootQAetxwQMayibUjs1AU',
    appId: '1:476947291063:ios:6371747d79f17ecde0a632',
    messagingSenderId: '476947291063',
    projectId: 'tiktok-abc-xyz',
    storageBucket: 'tiktok-abc-xyz.appspot.com',
    androidClientId:
        '476947291063-9r9crc1o5vrvnebk499c8qllvnsb79ee.apps.googleusercontent.com',
    iosClientId:
        '476947291063-ta4mq8mpcs4p3vkbgf5dp57d3u46og32.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnnykaLTNMF0t_qmYbfT_PwAtZF1vntsM',
    appId: '1:761169513958:web:66c0805f2683ecb9ccda27',
    messagingSenderId: '761169513958',
    projectId: 'my-tictok-practice',
    authDomain: 'my-tictok-practice.firebaseapp.com',
    storageBucket: 'my-tictok-practice.appspot.com',
    measurementId: 'G-16NHVDYFCR',
  );

}